Scripts/djsite/dfshop/urls.py
from django.urls import path, include

from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "dfshop"

urlpatterns = [
    path('goods/', views.goods, name='goods'),
    path('goods/<str:good>/good_details', views.good_details,
         name='good_details'),
    path('', views.indexView, name='home'),
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('login/', LoginView.as_view(next_page='dfshop:dashboard'),
         name='login_url'),
    path('register/', views.registerView, name='register_url'),
    # path('logout/', LogoutView.as_view(next_page='dfshop:dashboard'),
    #      name='logout'), #name = logout

    # path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('cart/', views.cartView, name='cart'),
]

Scripts/djsite/djsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('dfshop/', include('dfshop.urls')),
    path('admin/', admin.site.urls),
]

Scripts/djsite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # path('', views.index, name = "index"),
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('<int:question_id>/detail', views.detail, name='detail'),
]

Scripts/djsite/dfshop/models.py
from django.db import models
from django.contrib.auth.models import User

class Good(models.Model):
    category = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    material = models.CharField(max_length=20)
    imagelink = models.ImageField(upload_to='uploads/', default='', blank=True, null=True)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.material + " " + self.name

class Stock(models.Model):
    good = models.ForeignKey(Good, on_delete=models.CASCADE)
    quantityInStock = models.IntegerField(default=0)
    owner = models.CharField(max_length=150, default='admin')
    container = models.CharField(max_length=20, default='box')
    cart_owner = models.CharField(max_length=150, default='admin')

class Wallet(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    gold_quantity = models.IntegerField(default=0)

# Create your models here.

Scripts/djsite/dfshop/views.py
from .models import Good, Stock, Wallet
from django.shortcuts import render, redirect

from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

def goods(request):
    goods_list = Good.objects.all() #QuerySet
    stock = Stock.objects.all()

    if request.method == 'POST':
        """ take Add to cart input of a good,
            make a new Stock line: 
                change cart_owner to logged username,
                quantity_in_stock = Add to cart input
                owner's quantity reduce on Add to cart input
        """
        user = request.user
        for good in goods_list:
            add_to_cart = request.POST.get(str(good.id))
            # print(good.id, add_to_cart)
            if add_to_cart != None:
                add_to_cart = int(add_to_cart)
                owners_good = Stock.objects.get(good=good.id, cart_owner='admin')
                try:
                    buyers_good = Stock.objects.get(good=good.id, cart_owner=user.username)
                except (KeyError, Stock.DoesNotExist):
                    buyers_good = Stock.objects.create(good=good, cart_owner=user.username)

                owners_good.quantityInStock -= add_to_cart
                buyers_good.quantityInStock += add_to_cart
                owners_good.save()
                buyers_good.save()

    context = {'goods_list': goods_list,
               'stock': stock}
    return render(request, 'dfshop/goods.html', context)

def good_details(request, good):
    """
    good - good string from goods template.
    """
    good_split_list = good.rsplit(' ')
    good = Good.objects.get(material=good_split_list[0],
                            name__startswith=good_split_list[1]) #It should get a particular ID
    stock = Stock.objects.get(id=good.id)
    context = {'good': good,
                'stock': stock}
    return render(request, 'dfshop/good_details.html', context)


def indexView(request):
    return render(request, 'index.html')
@login_required()

def dashboardView(request):
    user = request.user
    try:
        wallet = user.wallet_set.get(owner=user.id)
    except (KeyError, Wallet.DoesNotExist):
        wallet = user.wallet_set.create()

    if request.method == 'POST':
        add_gold = int(request.POST.get('number'))
        wallet.gold_quantity += add_gold
        wallet.save()

    context = {'user':user,
               'wallet':wallet}
    return render(request, "dashboard.html", context)

# def loginView(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('login_url')


def registerView(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request, user)
            return redirect('dfshop:home')
        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])

            return render(request,
                          template_name='registration/register.html',
                          context={"form": form})

    form = UserCreationForm()
    return render(request,
                  template_name='registration/register.html',
                  context={"form": form})

def cartView(request):
    user = request.user
    stock = Stock.objects.filter(cart_owner=user.username)

    context = {'user':user,
               'stock':stock}
    return render(request, "cart.html", context)

# Create your views here.

Scripts/djsite/dfshop/templates/cart.html
{% extends 'index.html' %}

{% block content %}
<h3>Your cart</h3>
    {% if user.is_authenticated %}
        {% if stock %} 
        <!-- goods list in user's cart -->
        <table>
            <thead>
                <td>Good</td>
                <td>Price</td>
                <td>Quantity</td>
                <td>Delete</td>
            </thead>
            <tbody>
                {% for st in stock %}
                <tr>                
                    <td><a href="{% url 'dfshop:good_details' st.good %}">{{ st.good.name }}</a></td>
                    <td>{{ st.good.price }}</td>
                    <td>{{ st.quantityInStock }}</td>
                    <td><button>Delete</button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <h5>Your cart is empty yet. Feel free to <a href="{% url 'dfshop:goods' %}">fill</a> it</h5>
        {% endif %}
    {% else %}
        <h5>You are logged out. Please <a href="{% url 'dfshop:login_url' %}">login</a> to see your cart.</h5>
    {% endif %}
{% endblock %}

Scripts/djsite/dfshop/templates/dashboard.html
{% extends 'index.html' %}

{% block content %}
    {% if user.is_authenticated %}
    <div class="container">
    <h4>Welcome, {{user.username}} </h4>
    <p style="font-size: 155%;">Your wallet: {{wallet.gold_quantity}} gold</p>
    <form action="{% url 'dfshop:dashboard' %}" method="post">
        {% csrf_token %}
        <input type="number" name="number" min="0">
        <button>Add Gold</button>
        <!-- <input type="submit" value="Add Gold"> -->
    </form>
    {% else %}
    <h3>You are logged out</h3>
    {% endif %}
    </div>
{% endblock %}

Scripts/djsite/dfshop/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Prism CSS -->
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScrypt for Materialize CSS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <title>Umriliteb Fortress</title>
</head>
<body class="#bdbdbd grey lighten-1">
    <header>
        <nav>
            <div class="nav-wrapper #424242 grey darken-3">
                <ul id="nav-mobile" class="left hide-on-med-and-down">
                    <h5 class="brand-logo">Umriliteb Fortress</h5>
                    <p class="grey-text text-lighten-4" style="font-size: 155%;">Goods for Determination and Industry</p>
                </ul>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="{% url 'dfshop:home' %}">Home</a></li>
                    <li><a href="{% url 'dfshop:goods' %}">Goods</a></li>
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'dfshop:dashboard' %}">{{user.username}}</a></li>
                      <li><a href="{% url 'dfshop:cart' %}">Cart</a></li>
                      <li><a href="{% url 'dfshop:logout' %}">Logout</a></li>
                    {% else %}
                      <li><a href="{% url 'dfshop:login_url' %}">Login</a></li>
                      <li><a href="{% url 'dfshop:cart' %}">Cart</a></li>
                      <li><a href="{% url 'dfshop:register_url' %}">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main>
    <div class="container">
    {% block content %}
    <p>Latest fortress news</p>
    <p>Most popular goods</p>
    {% endblock %}
    </div>
    </main>
    <footer class="page-footer #212121 grey darken-4">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">Umriliteb Fortress</h5>
              <p class="grey-text text-lighten-4">Goods for Determination and Industry</p>
            </div>
            <div class="col l4 offset-l2 s12">
              <h5 class="white-text">Links</h5>
              <ul>
                <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-copyright">
          <div class="container">
          © 2022 Iron Forge Development
          <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
          </div>
        </div>
    </footer>
</body>
</html>